-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "breeze_cursors")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            size = 8,
        },
        rounding = 6,
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(e12885ff)", "rgba(34ccffee)"},
                angle = 45,
            },
        },
    },
})
